extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.build.json

env:
  node: true

overrides:
  - files:
      - stories/**/*.tsx
      - test/**/*.tsx
      - src/**/*.tsx
    extends:
      - eslint:recommended
      - plugin:import/errors
      - plugin:import/typescript
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:react/recommended
      - plugin:react-hooks/recommended
      - plugin:jsx-a11y/recommended
      - plugin:jest/recommended
      - plugin:testing-library/react
      - plugin:prettier/recommended
      - prettier
    parserOptions:
      project: ./tsconfig.json
      ecmaFeatures:
        jsx: true
    settings:
      react:
        version: detect
    env:
      browser: true
    rules:
      import/no-anonymous-default-export: off
      react/jsx-uses-react: off
      react/react-in-jsx-scope: off
      jsx-a11y/no-autofocus: off
      react/prop-types: off

rules:
  max-len:
    - error
    - code: 120
  '@typescript-eslint/lines-between-class-members':
    - error
    - always
    - exceptAfterSingleLine: true
  '@typescript-eslint/naming-convention':
    - error
    - selector: variable
      format:
        - camelCase
    - selector: variable
      modifiers:
        - const
      format:
        - camelCase
        - UPPER_CASE
        - PascalCase
    - selector: function
      format:
        - camelCase
        - PascalCase
    - selector: typeLike
      format:
        - PascalCase
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
